### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by nikrou** [swagindustries/Melodiia#43]
I read documentation in docs directory especially getting-stated file but I didin't find a way to access to the route "get all" for an object. I start reading documentation on openapi schema and didn't find how to define that entry point.

To be clear, I know how to have that route (read collection) but didn't find how to declare it in openapi file.

p.s: I create an issue with the idea to create a PR after.

**Comment by Nek-** [comment]
Closing in favor of #62
